### ISSUE TITLE
[BUG]Error on Login with 1.19.4

### ISSUE THREAD

**Issue by CloudeLecaw** [LoneDev6/Issues-Wraith#101]
**Describe the bug**
wenn a player logs in sometimes an error appears in console. The ineresting part is this does not happen to every player each time..

**To Reproduce**
1. use a paper 1.19.4 server with Wraith 2.3.5 and LoneDevLibs 1.0.24
2. login

**Expected behavior**
no error in console

**Screenshots**
```
[11:01:03] [Server thread/INFO]: Joined: bastirusti95 | Brands: [vanilla] | GameMode: SURVIVAL | World: world | /ww spectate bastirusti95 | UUID: ed5cd822-7e3b-417e-b80a-94371e6e888a | IP: /93.205.241.250:50135 
[11:01:07] [Timer-3/WARN]: Exception in thread "Timer-3" java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
[11:01:07] [Timer-3/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.NMS.Blocks.impl.v1_19_R3.a(SourceFile:29)
[11:01:07] [Timer-3/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.NMS.Blocks.Blocks.a(SourceFile:162)
[11:01:07] [Timer-3/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.b(SourceFile:982)
[11:01:07] [Timer-3/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.K(SourceFile:960)
[11:01:07] [Timer-3/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.ai(SourceFile:168)
[11:01:07] [Timer-3/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.bX.run(SourceFile:136)
[11:01:07] [Timer-3/WARN]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
[11:01:07] [Timer-3/WARN]: 	at java.base/java.util.TimerThread.run(Timer.java:516)
[11:01:07] [Timer-4/WARN]: Exception in thread "Timer-4" java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
[11:01:07] [Timer-4/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.NMS.Blocks.impl.v1_19_R3.a(SourceFile:29)
[11:01:07] [Timer-4/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.NMS.Blocks.Blocks.a(SourceFile:162)
[11:01:07] [Timer-4/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.b(SourceFile:982)
[11:01:07] [Timer-4/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.K(SourceFile:960)
[11:01:07] [Timer-4/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.ai(SourceFile:168)
[11:01:07] [Timer-4/WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.bX.run(SourceFile:136)
[11:01:07] [Timer-4/WARN]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
[11:01:07] [Timer-4/WARN]: 	at java.base/java.util.TimerThread.run(Timer.java:516)
```

**Info (please complete the following information):**
 - Server version: paper 1.19.4
 - Client version: vanilla 1.19.4
 - Plugin version: wraith 2.3.5.  LoneDevLibs 1.0.24

**Comment by CloudeLecaw** [comment]
```
[01:12:43 WARN]: Exception in thread "Timer-3" java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
at Wraith_2.3.5.jar//dev.lone.wraith.NMS.Blocks.impl.v1_19_R3.a(SourceFile:29)
[01:12:43 WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.NMS.Blocks.Blocks.a(SourceFile:162)
[01:12:43 WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.b(SourceFile:982)
[01:12:43 WARN]: 	
[01:12:43 WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.K(SourceFile:960)
[01:12:43 WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.ai(SourceFile:168)
[01:12:43 WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.bX.run(SourceFile:136)
[01:12:43 WARN]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
[01:12:43 WARN]: 	at java.base/java.util.TimerThread.run(Timer.java:516)
[01:12:43 WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.NMS.Blocks.impl.v1_19_R3.a(SourceFile:29)
[01:12:43 WARN]: Exception in thread "Timer-4" java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
[01:12:43 WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.NMS.Blocks.Blocks.a(SourceFile:162)
[01:12:43 WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.b(SourceFile:982)
[01:12:43 WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.K(SourceFile:960)
[01:12:43 WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.cc.ai(SourceFile:168)
[01:12:43 WARN]: 	at Wraith_2.3.5.jar//dev.lone.wraith.main.bX.run(SourceFile:136)
[01:12:43 WARN]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
[01:12:43 WARN]: 	at java.base/java.util.TimerThread.run(Timer.java:516)
```
