### ISSUE TITLE
The plugin currenty has no support for 1.20.2 to 1.21[BUG] 

### ISSUE THREAD

**Issue by CloudeLecaw** [LoneDev6/Issues-Wraith#106]
**Describe the bug**
The plugin ferfusses to load in 1.20.2 i aspect this  might need a fix of Lonedev Libs as well :3

**To Reproduce**
1. sart the server with latest 1.20.2 spigot build and some lonedev plugins

**Expected behavior**
wraith should load
```
[22:42:04] [Server thread/INFO]: [Wraith] Enabling Wraith v2.3.5c
[22:42:05] [Server thread/ERROR]: [Wraith] Error getting implementation for class dev.lone.wraith.NMS.Player.PlayerNMS - NMS v1_20_R2
[22:42:05] [Server thread/WARN]: java.lang.ClassNotFoundException: dev.lone.wraith.NMS.Player.impl.v1_20_R2
[22:42:05] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147)
[22:42:05] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[22:42:05] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[22:42:05] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[22:42:05] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:391)
[22:42:05] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:382)
[22:42:05] [Server thread/WARN]: 	at dev.lone.wraith.NMS.Nms.a(SourceFile:80)
[22:42:05] [Server thread/WARN]: 	at dev.lone.wraith.NMS.Nms.a(SourceFile:60)
[22:42:05] [Server thread/WARN]: 	at dev.lone.wraith.NMS.Player.PlayerNMS.<init>(SourceFile:28)
[22:42:05] [Server thread/WARN]: 	at dev.lone.wraith.NMS.Player.PlayerNMS.a(SourceFile:22)
[22:42:05] [Server thread/WARN]: 	at dev.lone.wraith.Main.onEnable(SourceFile:181)
[22:42:05] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[22:42:05] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[22:42:05] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[22:42:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:548)
[22:42:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:462)
[22:42:05] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:577)
[22:42:05] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:400)
[22:42:05] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[22:42:05] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:954)
[22:42:05] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298)
[22:42:05] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1623)
[22:42:05] [Server thread/INFO]: [Wraith] Disabling Wraith v2.3.5c
[22:42:05] [Server thread/ERROR]: Error occurred while disabling Wraith v2.3.5c (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "dev.lone.wraith.main.bU.ag()" because "dev.lone.wraith.Main.a" is null
	at dev.lone.wraith.Main.onDisable(SourceFile:429) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:268) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:367) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at dev.lone.wraith.NMS.Nms.a(SourceFile:99) ~[?:?]
	at dev.lone.wraith.NMS.Nms.a(SourceFile:60) ~[?:?]
	at dev.lone.wraith.NMS.Player.PlayerNMS.<init>(SourceFile:28) ~[?:?]
	at dev.lone.wraith.NMS.Player.PlayerNMS.a(SourceFile:22) ~[?:?]
	at dev.lone.wraith.Main.onEnable(SourceFile:181) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:548) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3886-Spigot-17ca32d-f0661c3]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:462) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3886-Spigot-17ca32d-f0661c3]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:577) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3886-Spigot-17ca32d-f0661c3]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:400) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3886-Spigot-17ca32d-f0661c3]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3886-Spigot-17ca32d-f0661c3]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:954) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3886-Spigot-17ca32d-f0661c3]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3886-Spigot-17ca32d-f0661c3]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[22:42:05] [Server thread/ERROR]: Error occurred while enabling Wraith v2.3.5c (Is it up to date?)
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:845) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:337) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:510) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:465) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:159) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:104) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at dev.lone.wraith.Main.onEnable(SourceFile:182) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:548) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3886-Spigot-17ca32d-f0661c3]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:462) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3886-Spigot-17ca32d-f0661c3]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:577) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3886-Spigot-17ca32d-f0661c3]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:400) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3886-Spigot-17ca32d-f0661c3]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3886-Spigot-17ca32d-f0661c3]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:954) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3886-Spigot-17ca32d-f0661c3]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3886-Spigot-17ca32d-f0661c3]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```

**Comment by CloudeLecaw** [comment]
Just want to inform that this error still exists with using LonedevLib 1.0.26
So it looks like Wraith itself might need an update.

**Comment by LoneDev6** [comment]
ty this will be worked on asap, sorry for the delay but this game code is changing so much on each update

**Comment by LoneDev6** [comment]
Issues to be solved on 1.20.2.
Mojang decided once again to fuck things up, they reimplemented the CustomPacketPayload logic.

- [ ] Fix Badlion compatibility
- [ ] Fix 5zig compatibility
- [ ] Fix Forge and Fabric handshake emulation
- [ ] Fix brand detection

I think the issue relies on the PluginChannels class of Spigot not working anymore as I don't get the onPluginMessageReceived called even if `minecraft:brand` channel listener was registered.

For now I'll wait for someone to post something on the Spigot forum, right now I have no solution.
I posted a thread on Spigot: https://www.spigotmc.org/threads/1-20-2-client-brand-detection-with-plugin-channel.621958/

**Comment by CloudeLecaw** [comment]
Many there is a solution? :3 Wraith currently is our last plugin that would need an update before we could change to 1.20.2 :3

**Comment by Gooisnotsocool** [comment]
So i was looking to purchase the plugin but, will there ever be 1.20.4 support or will we have to find alternatives like client detector?
this issue is pretty old now

**Comment by CloudeLecaw** [comment]
noone knows, we waited for a 1.20.4 Version
we waited for a 1.20.6 Version
and we might will wait fir a 1.21 Version

currently there is none and its not clear when a Version will come and what versions it will be support to.

**Comment by CloudeLecaw** [comment]
> So i was looking to purchase the plugin but, will there ever be 1.20.4 support or will we have to find alternatives like client detector? this issue is pretty old now

that doesnt matter if the issue is old or not. its there because there is still no version for it.

noone knows if and when it will come
- we waited for a 1.20.2 Version ....
- we waited for a 1.20.4 Version ....
- we waited for a 1.20.6 Version ....
- and we might will wait for a 1.21 Version, because minecraft 1.21 is relased soon.

currently there is none and its not clear when a Version will come and what versions it will be support to.
.
.
.
by the way: Client detector currently is not working on 1.20.4 and abouve. it loads but doenst block anything.

currently its under a rewrite and its also unclear when this will be ever released. we just know the new name is ClientDetectorPlus ...the plus might mentioned it will become Premium.

So if you think about buying the plugin now at the moment and your allready an 1.20.4 or up i would not recomment to buy it untril there may is an updated version one day.
