### ISSUE TITLE
[BUG] Wraith Plugin Viaversion 5.0.0 not work

### ISSUE THREAD

**Issue by mVtZWFu** [LoneDev6/Issues-Wraith#108]
**Describe the bug**

**To Reproduce**
1. Install the latest versions of Viaversion (+Viabackward) and Wraith,  Protocollib 5.0.0,  Packet Event )
2. Server Start
3. Check Wraith plugin status
4. Run Command ww
5. Error

**Expected behavior**
If update Viaversion the latest version, the Wraith plugin will not work.

**Screenshots**
Normal <= Viaversion 4.10.2
![1718841393-553012-20240620-085614](https://github.com/PluginBugs/Issues-Wraith/assets/76400529/cca45243-b26e-4a6d-b730-639501864c95)

ERROR plugin dose work Viaversion 5.0.0
![1718841564-923720-20240620-085906](https://github.com/PluginBugs/Issues-Wraith/assets/76400529/c49ec5a0-e1f5-441a-b02d-89cae88e82b9)

**Info (please complete the following information):**
 - Server version: 1.20.1
 - Client version: Fabric 1.20.1
 - Plugin version: latest

**Additional context**
Plaese Fix That!!

**Comment by mVtZWFu** [comment]
I'm waiting for this error to be fixed.

**Comment by mVtZWFu** [comment]
I've tested both 1.20.1 ~ 1.21, and the 

It only works if update VIaversion to the latest version.

**Comment by mVtZWFu** [comment]
WARNING: Using incubator modules: jdk.incubator.vector
Starting org.bukkit.craftbukkit.Main
System Info: Java 18 (Java HotSpot(TM) 64-Bit Server VM 18+36-2087) Host: Windows 10 10.0 (amd64)
Loading libraries, please wait...
[06:10:58 WARN]: resource-pack-id missing, using default of 0b2640fc-ec3b-3139-ad78-128ff2c8fdfc
[06:10:58 INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[06:11:00 INFO]: Loaded 1174 recipes
[06:11:00 INFO]: Loaded 1271 advancements
[06:11:00 INFO]: Starting minecraft server version 1.20.4
[06:11:00 INFO]: Loading properties
[06:11:00 INFO]: This server is running Purpur version git-Purpur-2176 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 6b1ee98 on HEAD)
[06:11:01 INFO]: Server Ping Player Sample Count: 0
[06:11:01 INFO]: Using 8 threads for Netty based IO
[06:11:01 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 12 worker threads, and gen parallelism of 12 threads
[06:11:01 INFO]: [Pufferfish] Max SIMD vector size on this system is 256 bits (int)
[06:11:01 INFO]: [Pufferfish] Max SIMD vector size on this system is 256 bits (float)
[06:11:01 INFO]: [Pufferfish] SIMD operations detected as functional. Will replace some operations with faster versions.
[06:11:01 INFO]: Default game type: SURVIVAL
[06:11:01 INFO]: Generating keypair
[06:11:01 INFO]: Starting Minecraft server on 192.168.0.114:25566
[06:11:01 INFO]: Using default channel type
[06:11:01 INFO]: Paper: Using Java compression from Velocity.
[06:11:01 INFO]: Paper: Using Java cipher from Velocity.
[06:11:01 INFO]: [ViaVersion] Loading server plugin ViaVersion v5.0.1
[06:11:01 INFO]: [ViaVersion] ViaVersion 5.0.1 is now loaded. Registering protocol transformers and injecting...
[06:11:02 INFO]: [ViaVersion] Loading block connection mappings ...
[06:11:02 INFO]: [ViaVersion] Using FastUtil Long2ObjectOpenHashMap for block connections
[06:11:02 INFO]: [ViaBackwards] Loading translations...
[06:11:02 INFO]: [ViaBackwards] Registering protocols...
[06:11:02 INFO]: [LoneLibs] Loading server plugin LoneLibs v1.0.54
[06:11:02 INFO]: [ViaBackwards] Loading server plugin ViaBackwards v5.0.1
[06:11:02 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.2.0-SNAPSHOT-679
[06:11:03 INFO]: [Wraith] Loading server plugin Wraith v2.3.5c
[06:11:03 INFO]: Server permissions file permissions.yml is empty, ignoring it
[06:11:03 INFO]: [LoneLibs] Enabling LoneLibs v1.0.54
[06:11:03 INFO]: [ProtocolLib] Enabling ProtocolLib v5.2.0-SNAPSHOT-679
[06:11:03 INFO]: Preparing level "world"
[06:11:04 INFO]: [ViaVersion] Enabling ViaVersion v5.0.1
[06:11:04 INFO]: [ViaVersion] ViaVersion detected server version: 1.20.3-1.20.4 (765)
[06:11:04 INFO]: [ViaBackwards] Enabling ViaBackwards v5.0.1
[06:11:04 INFO]: [Wraith] Enabling Wraith v2.3.5c
[06:11:04 ERROR]: [Wraith] Error getting implementation for class dev.lone.wraith.NMS.Player.PlayerNMS - NMS v1_20_R3
[06:11:04 WARN]: java.lang.ClassNotFoundException: dev.lone.wraith.NMS.Player.impl.v1_20_R3
[06:11:04 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:199)
[06:11:04 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:166)
[06:11:04 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[06:11:04 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[06:11:04 WARN]:        at java.base/java.lang.Class.forName(Class.java:383)
[06:11:04 WARN]:        at java.base/java.lang.Class.forName(Class.java:376)
[06:11:04 WARN]:        at Wraith_2.3.5c.jar//dev.lone.wraith.NMS.Nms.a(SourceFile:80)
[06:11:04 WARN]:        at Wraith_2.3.5c.jar//dev.lone.wraith.NMS.Nms.a(SourceFile:60)
[06:11:04 WARN]:        at Wraith_2.3.5c.jar//dev.lone.wraith.NMS.Player.PlayerNMS.<init>(SourceFile:28)
[06:11:04 WARN]:        at Wraith_2.3.5c.jar//dev.lone.wraith.NMS.Player.PlayerNMS.a(SourceFile:22)
[06:11:04 WARN]:        at Wraith_2.3.5c.jar//dev.lone.wraith.Main.onEnable(SourceFile:181)
[06:11:04 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[06:11:04 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188)
[06:11:04 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[06:11:04 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[06:11:04 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653)
[06:11:04 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564)
[06:11:04 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675)
[06:11:04 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435)
[06:11:04 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:346)
[06:11:04 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1146)
[06:11:04 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[06:11:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[06:11:04 INFO]: [Wraith] Disabling Wraith v2.3.5c
[06:11:04 ERROR]: Error occurred while disabling Wraith v2.3.5c
java.lang.NullPointerException: Cannot invoke "dev.lone.wraith.main.bU.ag()" because "dev.lone.wraith.Main.a" is null
        at dev.lone.wraith.Main.onDisable(SourceFile:429) ~[Wraith_2.3.5c.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:223) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at dev.lone.wraith.NMS.Nms.a(SourceFile:99) ~[Wraith_2.3.5c.jar:?]
        at dev.lone.wraith.NMS.Nms.a(SourceFile:60) ~[Wraith_2.3.5c.jar:?]
        at dev.lone.wraith.NMS.Player.PlayerNMS.<init>(SourceFile:28) ~[Wraith_2.3.5c.jar:?]
        at dev.lone.wraith.NMS.Player.PlayerNMS.a(SourceFile:22) ~[Wraith_2.3.5c.jar:?]
        at dev.lone.wraith.Main.onEnable(SourceFile:181) ~[Wraith_2.3.5c.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[06:11:04 ERROR]: Error occurred while enabling Wraith v2.3.5c (Is it up to date?)
java.lang.NoClassDefFoundError: dev/lone/wraith/NMS/Server/ServerNMS
        at dev.lone.wraith.Main.onEnable(SourceFile:182) ~[Wraith_2.3.5c.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: dev.lone.wraith.NMS.Server.ServerNMS
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:199) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:166) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 13 more
[06:11:04 INFO]: Running delayed init tasks
[06:11:04 INFO]: Done (4.290s)! For help, type "help"
[06:11:04 INFO]: Stopping server
[06:11:04 INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[06:11:04 INFO]: [ProtocolLib] Disabling ProtocolLib v5.2.0-SNAPSHOT-679
[06:11:04 INFO]: [ViaBackwards] Disabling ViaBackwards v5.0.1
[06:11:04 INFO]: [LoneLibs] Disabling LoneLibs v1.0.54
[06:11:04 INFO]: [ViaVersion] Disabling ViaVersion v5.0.1
[06:11:04 INFO]: [ViaVersion] ViaVersion is disabling, if this is a reload and you experience issues consider rebooting.
[06:11:04 WARN]: [LoneLibs] Plugin LoneLibs v1.0.54 generated an exception while executing task 2
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:550) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:226) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:211) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:175) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTask(CraftScheduler.java:144) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at dev.lone.LoneLibs.Metrics.<init>(Metrics.java:153) ~[LoneLibs.jar:?]
        at dev.lone.LoneLibs.Main.lambda$onEnable$0(Main.java:24) ~[LoneLibs.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by CloudeLecaw** [comment]
might you noticed
Wraith broke allready after 1.20.1...

You thought its because of via version? well no its not
The plugin just broke after 1.20.1 and never got an update since that.

See here
https://github.com/PluginBugs/Issues-Wraith/issues/106

so what is your server?
your error sais 1.20.4  so you can take off Wraith for the first. until may one day a patch come out.. if it ever will..

**Comment by mVtZWFu** [comment]
The same is true for Viaversion 5.0.0 on 1.20.1. Viaversion 4.10.2 does not have the problem, but hopefully it will be fixed.

**Comment by mVtZWFu** [comment]
Is there another plugin that works almost exactly the same way as this one?
