### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by humisan** [LoneDev6/Issues-Wraith#109]
**Describe the bug**
I have downloaded all the necessary plugins and updated them to the latest version, but the plugins do not start

**To Reproduce**
Start the server with purpur-1.20.1-2062 and install ViaVersion 5.0.0, Wraith_2.3.5c and ProtocolLib 5.2.0 on the server

**Expected behavior**
Plugin does not load

**Screenshots**
```
[04:05:02 ERROR]: Error occurred while enabling Wraith v2.3.5c (Is it up to date?)
java.lang.NoClassDefFoundError: us/myles/ViaVersion/protocols/protocol1_13to1_12_2/Protocol1_13To1_12_2
        at dev.lone.wraith.main.A.<init>(SourceFile:35) ~[Wraith_2.3.5c.jar:?]
        at dev.lone.wraith.main.A.p(SourceFile:59) ~[Wraith_2.3.5c.jar:?]
        at dev.lone.wraith.Main.onEnable(SourceFile:216) ~[Wraith_2.3.5c.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at com.rylinaux.plugman.util.BukkitPluginUtil.enable(BukkitPluginUtil.java:135) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.util.PaperPluginUtil.enable(PaperPluginUtil.java:157) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.command.RestartCommand.execute(RestartCommand.java:127) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:97) ~[PlugManX.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1001) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:986) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:540) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1420) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: us.myles.ViaVersion.protocols.protocol1_13to1_12_2.Protocol1_13To1_12_2
        ... 21 more
[04:05:02 INFO]: [Wraith] Disabling Wraith v2.3.5c
[04:05:02 ERROR]: Error occurred (in the plugin loader) while disabling Wraith v2.3.5c (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "dev.lone.wraith.main.bU.ag()" because "dev.lone.wraith.Main.a" is null
        at dev.lone.wraith.Main.onDisable(SourceFile:429) ~[Wraith_2.3.5c.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at com.rylinaux.plugman.util.BukkitPluginUtil.enable(BukkitPluginUtil.java:135) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.util.PaperPluginUtil.enable(PaperPluginUtil.java:157) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.command.RestartCommand.execute(RestartCommand.java:127) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:97) ~[PlugManX.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1001) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:986) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:540) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1420) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by humisan** [comment]
When will this bug be fixed? I have never seen a plugin that I paid money for that was this bad 💀
