### ISSUE TITLE
Does not load [BUG] 

### ISSUE THREAD

**Issue by ProjectRoxan** [LoneDev6/Issues-Wraith#110]
**Describe the bug**
The plugin disables itself on server startup.

**To Reproduce**
4. [10:32:12 INFO]: [Wraith] Disabling Wraith v2.3.5c
[10:32:12 ERROR]: Error occurred (in the plugin loader) while disabling Wraith v2.3.5c (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "dev.lone.wraith.main.bU.ag()" because "dev.lone.wraith.Main.a" is null
        at dev.lone.wraith.Main.onDisable(SourceFile:429) ~[Wraith_2.3.5c.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[pufferfish-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[pufferfish-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:556) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:467) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1106) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Expected behavior**
The plugin disables itself on server startup

**Screenshots**
![kép](https://github.com/user-attachments/assets/e4b565e2-469e-4855-acfe-7995222bf983)

**Info (please complete the following information):**
 - Server version: (Pufferfish 1.19.4)
 - Client version: (Fabric 1.20.1)
 - Plugin version: (latest)

**Additional context**
I tested all core but does not load the plugin 
Now i use PufferFish

**Comment by mVtZWFu** [comment]
You need to lower viaversion to 4.10.2 to make it work.
