### ISSUE TITLE
ERRO IN START SERVER 1.16.2 [BUG] 

### ISSUE THREAD

**Issue by JavituRec** [LoneDev6/Issues-Wraith#13]
**Describe the bug**
Error in server start

Server thread/ERROR]: Error occurred while enabling Wraith v2.0.27 (Is it up to date?)
java.lang.NullPointerException: null
	at dev.lone.wraith.b.b.b.<init>(SourceFile:45) ~[?:?]
	at dev.lone.wraith.b.d.a(SourceFile:92) ~[?:?]
	at dev.lone.wraith.Main.onEnable(SourceFile:279) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-137]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-137]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-137]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-137]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-137]
	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-137]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-137]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941) ~[patched_1.16.1.jar:git-Paper-137]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-137]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Info (please complete the following information):**
 - Server version: 1.16.2 last paperspigot #137
 - Plugin version: 2.0.27

**Comment by LoneDev6** [comment]
Let me know if it's still an issue
