### ISSUE TITLE
[BUG] error on login in 2.1.0

### ISSUE THREAD

**Issue by CloudeLecaw** [LoneDev6/Issues-Wraith#31]
>.... [01:37:58 INFO]: Cloude_Lecaw[/94.139.28.154:63553] logged in with entity id 3452 at ([world]1759.5678674371186, 63.0, 1650.1578773641438)
>.... [01:38:02 WARN]: Exception in thread "Timer-3" java.util.NoSuchElementException
>.... [01:38:02 WARN]: at org.bukkit.craftbukkit.v1_16_R3.util.UnsafeList$Itr.next(UnsafeList.java:263)
>.... [01:38:02 WARN]: at dev.lone.wraith.j.a.b.a.j.j(SourceFile:24)
>.... [01:38:02 WARN]: at dev.lone.wraith.h.i.ad(SourceFile:791)
>.... [01:38:02 WARN]: at dev.lone.wraith.h.i.T(SourceFile:168)
>.... [01:38:02 WARN]: at dev.lone.wraith.h.d.run(SourceFile:109)
>.... [01:38:02 WARN]: at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
>.... [01:38:02 WARN]: at java.base/java.util.TimerThread.run(Timer.java:506)

it result that we do not see the line we saw before where it noticed the client in 2.0.34

on he first join of  a player we sometimes get also this one from wraith

```
>.... [02:23:37 WARN]: [Wraith] Plugin Wraith v2.1.0 generated an exception while executing task 361
java.lang.ArrayIndexOutOfBoundsException: Index 11 out of bounds for length 10
at java.util.ArrayList.add(ArrayList.java:487) ~[?:?]
at java.util.ArrayList.add(ArrayList.java:499) ~[?:?]
at dev.lone.wraith.h.i.d(SourceFile:476) ~[?:?]
at dev.lone.wraith.h.c.run(SourceFile:79) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-705]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-705]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-705]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by LoneDev6** [comment]
Thanks this happens because of thread desync because of some optimizations, I will fix that in the next update
