### ISSUE TITLE
Players enter the server and report an error.

### ISSUE THREAD

**Issue by mojiansheng** [LoneDev6/Issues-Wraith#34]
Paper-682 (MC: 1.16.5) Wraith v2.1.1
http://222.89.70.209:808/nextcloud/index.php/s/y4dcYntLBCHT2Ts/download/2021-05-20-8.log.gz
The full log is in the URL above.

[22:38:40] [Server thread/INFO]: + huimengyuan 加入了大厅
[22:38:40] [Server thread/INFO]: huimengyuan[/14.111.58.71:55266] logged in with entity id 357 at ([world]1110.5, 17.0, -146.5)
[22:38:41] [Server thread/INFO]: [CMI] CMIB proxy plugin detected
[22:38:41] [Server thread/INFO]: Joined -> huimengyuan | Brands: [forge] | ChatCraft: YES | GameMode: SURVIVAL | World: world | Location: /tppos 1110 17 -146 | UUID: c78fd804-5c39-36dc-ab1b-de57a81a7dc7 | IP: /14.111.58.71:55266
[22:38:42] [Craft Scheduler Thread - 5/WARN]: [Wraith] Plugin Wraith v2.1.1 generated an exception while executing task 725
java.lang.NullPointerException: null
	at dev.lone.wraith.j.a.b.a.l(SourceFile:72) ~[?:?]
	at dev.lone.wraith.h.j.ag(SourceFile:1069) ~[?:?]
	at dev.lone.wraith.e.i.F(SourceFile:47) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[Paper.jar:git-Paper-682]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[Paper.jar:git-Paper-682]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[Paper.jar:git-Paper-682]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[22:38:43] [Craft Scheduler Thread - 29/WARN]: [Wraith] Plugin Wraith v2.1.1 generated an exception while executing task 725
java.lang.NullPointerException: null
	at dev.lone.wraith.j.a.b.a.l(SourceFile:72) ~[?:?]
	at dev.lone.wraith.h.j.ag(SourceFile:1069) ~[?:?]
	at dev.lone.wraith.e.i.F(SourceFile:47) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[Paper.jar:git-Paper-682]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[Paper.jar:git-Paper-682]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[Paper.jar:git-Paper-682]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[22:38:43] [Server thread/WARN]: [Wraith] Task #719 for Wraith v2.1.1 generated an exception
java.lang.NullPointerException: null
	at dev.lone.wraith.h.j.ad(SourceFile:799) ~[?:?]
	at dev.lone.wraith.h.j.U(SourceFile:142) ~[?:?]
	at dev.lone.wraith.h.d.run(SourceFile:98) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[Paper.jar:git-Paper-682]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[Paper.jar:git-Paper-682]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1424) ~[Paper.jar:git-Paper-682]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[Paper.jar:git-Paper-682]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1339) ~[Paper.jar:git-Paper-682]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1127) ~[Paper.jar:git-Paper-682]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[Paper.jar:git-Paper-682]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[22:38:43] [Server thread/WARN]: [Wraith] Task #748 for Wraith v2.1.1 generated an exception
java.lang.NullPointerException: null
	at dev.lone.wraith.h.j.ad(SourceFile:799) ~[?:?]
	at dev.lone.wraith.h.j.U(SourceFile:142) ~[?:?]
	at dev.lone.wraith.h.d.run(SourceFile:98) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[Paper.jar:git-Paper-682]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[Paper.jar:git-Paper-682]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1424) ~[Paper.jar:git-Paper-682]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[Paper.jar:git-Paper-682]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1339) ~[Paper.jar:git-Paper-682]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1127) ~[Paper.jar:git-Paper-682]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[Paper.jar:git-Paper-682]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[22:38:43] [Timer-4/WARN]: Exception in thread "Timer-4" Exception in thread "Timer-3" java.lang.NoClassDefFoundError: Could not initialize class dev.lone.wraith.j.a.a.a
[22:38:43] [Timer-4/WARN]: 	at dev.lone.wraith.h.j.b(SourceFile:985)
[22:38:43] [Timer-4/WARN]: 	at dev.lone.wraith.h.j.J(SourceFile:963)
[22:38:43] [Timer-4/WARN]: 	at dev.lone.wraith.h.j.V(SourceFile:171)
[22:38:43] [Timer-4/WARN]: 	at dev.lone.wraith.h.e.run(SourceFile:131)
[22:38:43] [Timer-4/WARN]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[22:38:43] [Timer-4/WARN]: 	at java.base/java.util.TimerThread.run(Timer.java:506)
[22:38:43] [Timer-3/WARN]: java.lang.ExceptionInInitializerError
[22:38:43] [Timer-3/WARN]: 	at dev.lone.wraith.h.j.b(SourceFile:985)
[22:38:43] [Timer-3/WARN]: 	at dev.lone.wraith.h.j.J(SourceFile:963)
[22:38:43] [Timer-3/WARN]: 	at dev.lone.wraith.h.j.V(SourceFile:171)
[22:38:43] [Timer-3/WARN]: 	at dev.lone.wraith.h.e.run(SourceFile:131)
[22:38:43] [Timer-3/WARN]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[22:38:43] [Timer-3/WARN]: 	at java.base/java.util.TimerThread.run(Timer.java:506)
[22:38:43] [Timer-3/WARN]: Caused by: java.lang.NullPointerException
[22:38:43] [Timer-3/WARN]: 	at dev.lone.wraith.j.a.a.a.<clinit>(SourceFile:19)
[22:38:43] [Server thread/WARN]: [Wraith] Task #719 for Wraith v2.1.1 generated an exception
java.lang.NullPointerException: null
	at dev.lone.wraith.h.j.ad(SourceFile:799) ~[?:?]
	at dev.lone.wraith.h.j.U(SourceFile:142) ~[?:?]
	at dev.lone.wraith.h.d.run(SourceFile:98) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[Paper.jar:git-Paper-682]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[Paper.jar:git-Paper-682]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1424) ~[Paper.jar:git-Paper-682]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[Paper.jar:git-Paper-682]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1339) ~[Paper.jar:git-Paper-682]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1127) ~[Paper.jar:git-Paper-682]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[Paper.jar:git-Paper-682]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by LoneDev6** [comment]
try to temporarily remove PostMan plugin and restart.
let me know
