### ISSUE TITLE
New 2.2.0 does not start[BUG] 

### ISSUE THREAD

**Issue by CloudeLecaw** [LoneDev6/Issues-Wraith#36]
**Describe the bug**

Well what should insay, even with a fresh folder the plugin does not load in version 2.2.0

We are using paper 1.16.5 and java 11 on out server.

```
[20:37:14] [Server thread/INFO]: [Wraith] Enabling Wraith v2.2.0
[20:37:14] [Server thread/WARN]: [Wraith] Loaded class org.apache.commons.io.FileUtils from PlugMan v2.2.2 which is not a depend, softdepend or loadbefore of this plugin.
[20:37:14] [Server thread/INFO]: â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ
[20:37:14] [Server thread/INFO]: â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ
[20:37:14] [Server thread/INFO]: â–ˆâ–ˆâ–€â–ˆâ–ˆâ–€â–ˆ Wraith > haunts every hacker
[20:37:14] [Server thread/INFO]: â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ Version: 2.2.0
[20:37:14] [Server thread/INFO]: â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ
[20:37:14] [Server thread/WARN]: [Wraith] It's advised to install PacketLimiter to block packet spam and lag (nuke, crashers...). Download: https://bit.ly/wrpacklim
[20:37:14] [Server thread/INFO]: [Wraith] Found version v1_16_R3
[20:37:14] [Server thread/ERROR]: Error occurred while enabling Wraith v2.2.0 (Is it up to date?)
java.lang.IllegalArgumentException: Channel must contain : separator (attempted to use MC|Brand)
	at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:503) ~[patched_1.16.5.jar:git-Paper-740]
	at org.bukkit.plugin.messaging.StandardMessenger.registerIncomingPluginChannel(StandardMessenger.java:216) ~[patched_1.16.5.jar:git-Paper-740]
	at dev.lone.wraith.h.e.a(SourceFile:16) ~[?:?]
	at dev.lone.wraith.b.a.b.i.<init>(SourceFile:22) ~[?:?]
	at dev.lone.wraith.b.a.b.f.<init>(SourceFile:130) ~[?:?]
	at dev.lone.wraith.b.d.a(SourceFile:76) ~[?:?]
	at dev.lone.wraith.Main.onEnable(SourceFile:357) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-740]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-740]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-740]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-740]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-740]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:593) ~[patched_1.16.5.jar:git-Paper-740]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-740]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1068) ~[patched_1.16.5.jar:git-Paper-740]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-740]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[20:37:14] [Server thread/INFO]: [Wraith] Disabling Wraith v2.2.0
```

**Comment by myavuzokumus** [comment]
Yeah, i have same problem. @LoneDev6

**Comment by CloudeLecaw** [comment]
Its fixed in V.2.2.1 :-)
