### ISSUE TITLE
[BUG] login with Bedrock-Edition on Geyser configurated servers

### ISSUE THREAD

**Issue by CloudeLecaw** [LoneDev6/Issues-Wraith#40]
When setup your server with Geyser so bedrock clients can connect you get an error in the console instead of the usal branding scan in loginfo
 Server: PaperMC 1.16.5 with Java 11.0.10

```
[01:53:37] [Server thread/INFO]: *Kolumir[/94.139.28.154:44841] logged in with entity id 26389 at ([tutorial]-121.94962, 64.0, 98.45933)
[01:53:39] [Server thread/WARN]: [Wraith] Task #453050 for Wraith v2.2.2 generated an exception
java.lang.NullPointerException: null
    at dev.lone.wraith.b.a.b.c.u(SourceFile:673) ~[?:?]
    at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-768]
    at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-768]
    at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1427) ~[patched_1.16.5.jar:git-Paper-768]
    at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-768]
    at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-768]
    at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-768]
    at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-768]
    at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by LoneDev6** [comment]
Will be fixed today, thanks
