### ISSUE TITLE
[BUG] Teleport event problem

### ISSUE THREAD

**Issue by myavuzokumus** [LoneDev6/Issues-Wraith#44]
```
> ww testclient deserke
[15:18:20 INFO]: Oyuncuya hile denetleme gönderildi.
[15:18:20 INFO]: Joined: deserke | Brands: [vanilla] | Account: UNKNOWN | GameMode: ADVENTURE | World: world | /ww spectate deserke | UUID: b529dd7f-1edf-3dc1-97f3-19253e4ee90f | IP: 127.0.0.1
[15:18:22 INFO]: SCHile » This player is probably not using cheats, they didn't fail the test
[15:18:22 ERROR]: Could not pass event AsyncPlayerChatEvent to Wraith v2.2.2
[15:18:22 ERROR]: Suspected Plugins:
[15:18:22 ERROR]:       Wraith{enabled,ver=2.2.2,path=plugins\Wraith.jar}
[15:18:22 ERROR]: Exception details below:
java.lang.IllegalStateException: PlayerTeleportEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:616) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.teleport(CraftPlayer.java:903) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftEntity.teleport(CraftEntity.java:544) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
        at dev.lone.wraith.b.d.a(SourceFile:382) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor211.execute(Unknown Source) ~[?:?]        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:223) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
        at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:105) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:63) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
        at net.minecraft.server.v1_16_R3.PlayerConnection.chat(PlayerConnection.java:2229) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2144) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2082) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:44) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

**Info (please complete the following information):**
 - Server version: 1.16.5
 - Client version: 1.16.5
 - Plugin version: 2.2.2

**Comment by LoneDev6** [comment]
Will be fixed, thanks
