### ISSUE TITLE
[BUG]issue with wraith on startup in 1.17

### ISSUE THREAD

**Issue by CloudeLecaw** [LoneDev6/Issues-Wraith#45]
A little Update for 1,17 might be needed

LoneDevLib 1.0.12
PaperMC 1.17
Protocollib 4.6.0-Build 520 (version for 1.17)
```
14:52:24] [Server thread/INFO]: [Wraith] Enabling Wraith v2.2.3
[14:52:25] [Server thread/INFO]: ???????
[14:52:25] [Server thread/INFO]: ???????
[14:52:25] [Server thread/INFO]: ??????? Wraith > haunts every hacker
[14:52:25] [Server thread/INFO]: ??????? Version: 2.2.3
[14:52:25] [Server thread/INFO]: ???????
[14:52:25] [Server thread/WARN]: [Wraith] It's advised to install PacketLimiter to block packet spam and lag (nuke, crashers...). Download: https://bit.ly/wrpacklim
[14:52:25] [Thread-15/WARN]: [PermissionsEx] The updater could not find any files for the project id 31279
[14:52:25] [Server thread/WARN]: [ProtocolLib] [PacketFilterManager] [Wraith] Unsupported client packet in current Minecraft version: TRANSACTION[PLAY, CLIENT, 255, classNames: [net.minecraft.network.protocol.game.PacketPlayInTransaction, net.minecraft.network.protocol.game.ServerboundTransactionPacket, net.minecraft.network.play.client.CPacketConfirmTransaction] (unregistered)]
[14:52:25] [Server thread/WARN]: [ProtocolLib] [PacketFilterManager] [Wraith] Unsupported server packet in current Minecraft version: TRANSACTION[PLAY, SERVER, 246, classNames: [net.minecraft.network.protocol.game.PacketPlayOutTransaction, net.minecraft.network.protocol.game.ClientboundTransactionPacket, net.minecraft.network.play.server.SPacketConfirmTransaction] (unregistered)]
[14:52:25] [Server thread/INFO]: [Wraith] Found version v1_17_R1
[14:52:25] [Server thread/ERROR]: Error occurred while enabling Wraith v2.2.3 (Is it up to date?)
java.lang.RuntimeException: Failed to find EntityPlayer class
	at dev.lone.wraith.OtherPlugins.net.badlion.blcmodapibukkit.a.a.<init>(SourceFile:79) ~[?:?]
	at dev.lone.wraith.OtherPlugins.net.badlion.blcmodapibukkit.a.a(SourceFile:44) ~[?:?]
	at dev.lone.wraith.b.a.b.f.<init>(SourceFile:119) ~[?:?]
	at dev.lone.wraith.b.d.a(SourceFile:77) ~[?:?]
	at dev.lone.wraith.Main.onEnable(SourceFile:359) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Paper-"1830de5"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Paper-"1830de5"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-"1830de5"]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Paper-"1830de5"]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Paper-"1830de5"]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643) ~[patched_1.17.jar:git-Paper-"1830de5"]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:303) ~[patched_1.17.jar:git-Paper-"1830de5"]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-"1830de5"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"1830de5"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[14:52:25] [Server thread/INFO]: [Wraith] Disabling Wraith v2.2.3
[14:52:25] [Server thread/INFO]: Error Unable to handle disabled plugin. (java.lang.IllegalArgumentException: value already present: null) occured in com.comphenix.protocol.injector.PacketFilterManager@13003970.
[14:52:25] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to handle disabled plugin.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: value already present: null
  	at com.google.common.collect.HashBiMap.put(HashBiMap.java:287)
  	at com.google.common.collect.HashBiMap.put(HashBiMap.java:262)
  	at com.comphenix.protocol.injector.netty.ProtocolRegistry._associate(ProtocolRegistry.java:118)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:177)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:139)
  	at com.comphenix.protocol.concurrency.PacketTypeSet.getPacketClass(PacketTypeSet.java:82)
  	at com.comphenix.protocol.concurrency.PacketTypeSet.removeType(PacketTypeSet.java:58)
  	at com.comphenix.protocol.injector.netty.ProtocolInjector$4.removePacketHandler(ProtocolInjector.java:399)
  	at com.comphenix.protocol.injector.PacketFilterManager.disablePacketFilters(PacketFilterManager.java:601)
  	at com.comphenix.protocol.injector.PacketFilterManager.removePacketListener(PacketFilterManager.java:486)
  	at com.comphenix.protocol.injector.PacketFilterManager.removePacketListeners(PacketFilterManager.java:498)
  	at com.comphenix.protocol.injector.PacketFilterManager.onPluginDisabled(PacketFilterManager.java:957)
  	at com.comphenix.protocol.injector.PacketFilterManager.access$600(PacketFilterManager.java:71)
  	at com.comphenix.protocol.injector.PacketFilterManager$3.onPluginDisabled(PacketFilterManager.java:913)
  	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
  	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
  	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
  	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
  	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399)
  	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533)
  	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374)
  	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
  	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
  	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
  	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643)
  	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:303)
  	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
  	at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters: 
    org.bukkit.event.server.PluginDisableEvent@62ffa698[
      plugin=Wraith v2.2.3
      name=<null>
      async=false
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@13003970[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@c5496ee
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@5c241192
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@20c5091a
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@321c6fcb
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1ad77c80
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.7.0-SNAPSHOT-b520, pluginEnabled=true, url=plugins\ProtocolLib_4.6.0-Build520.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@668346c9
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-"1830de5",minecraftVersion=1.17}
        library=ProtocolLib v4.7.0-SNAPSHOT-b520
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@3fb556f6
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@29d7e73e
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@fa1dc16
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.17.0)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.PacketFilterManager@13003970[
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@c5496ee
      packetListeners=[]
      packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@5c241192
      playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@20c5091a
      inputBufferedPackets=[]
      recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@321c6fcb
      sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1ad77c80
      hasClosed=false
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.7.0-SNAPSHOT-b520, pluginEnabled=true, url=plugins\ProtocolLib_4.6.0-Build520.jar}
      reporter=com.comphenix.protocol.ProtocolLib$1@668346c9
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-"1830de5",minecraftVersion=1.17}
      library=ProtocolLib v4.7.0-SNAPSHOT-b520
      asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@3fb556f6
      knowsServerPackets=true
      knowsClientPackets=true
      phaseLoginCount=0
      phasePlayingCount=0
      packetCreation=false
      nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@29d7e73e
      pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@fa1dc16
      hasRecycleDistance=true
      minecraftVersion=(MC: 1.17.0)
      debug=false
    ]
  Version:
    ProtocolLib v4.7.0-SNAPSHOT-b520
  Java Version:
    16.0.1
  Server:
    git-Paper-"1830de5" (MC: 1.17)
```

**Comment by myk3sr** [comment]
I can confirm not working paper 1.17

**Comment by CloudeLecaw** [comment]
Looks like we have ti wait a bit for the wraith Update..
