### ISSUE TITLE
[BUG] Plugin Wraith v2.0.5 generated an exception whilst handling plugin message java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by Blueeyestar** [LoneDev6/Issues-Wraith#5]
Paper version git-Paper-39 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

after every start the error appears

>.... [11:09:08 WARN]: [Wraith] Plugin Wraith v2.0.5 generated an exception whilst handling plugin message
java.lang.NullPointerException: null
at dev.lone.wraith.b.a.b.b.onPluginMessageReceived(SourceFile:118) ~[?:?]
at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[patched_1.16.1.jar:git-Paper-39]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2765) ~[patched_1.16.1.jar:git-Paper-39]
at net.minecraft.server.v1_16_R1.PacketPlayInCustomPayload.a(SourceFile:44) ~[patched_1.16.1.jar:git-Paper-39]
at net.minecraft.server.v1_16_R1.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.16.1.jar:git-Paper-39]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-39]
at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-39]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-39]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-39]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-39]
at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-39]
at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-39]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-39]
at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1203) ~[patched_1.16.1.jar:git-Paper-39]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-39]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-39]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by LoneDev6** [comment]
I will post an update today, let me know if it fixes the issue, thanks!
