### ISSUE TITLE
[BUG] Generated too many classes

### ISSUE THREAD

**Issue by myavuzokumus** [LoneDev6/Issues-Wraith#55]
**Describe the bug**
```
[08:40:39] [Server thread/INFO]: Joined: blabla | Brands: [vanilla (Velocity)] | GameMode: ADVENTURE | World: world | /ww spectate blabla | UUID: blabla | IP: blabla
[08:40:44] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 5094ms or 101 ticks behind
[08:40:46] [Craft Scheduler Thread - 2016 - AuthMe/INFO]: [AuthMe] blabla logged in blabla
[08:40:46] [Server thread/INFO]: Sending client test.
[08:41:15] [Paper Watchdog Thread/WARN]: Exception in thread "Paper Watchdog Thread" Exception in thread "Timer-2" java.lang.OutOfMemoryErrorjava.lang.OutOfMemoryError: : Java heap spaceJava heap space
[08:41:15] [Timer-2/WARN]: 
[08:41:15] [Netty Epoll Server IO #0/WARN]: [ProtocolLib] [StructureCompiler] Generated too many classes (count: 13)
[08:41:15] [Paper Watchdog Thread/WARN]: 	at org.spigotmc.WatchdogThread.run(WatchdogThread.java:189)
[08:41:15] [Timer-2/WARN]: 	at net.minecraft.world.phys.Vec3D.add(Vec3D.java:83)
[08:41:15] [Timer-2/WARN]: 	at net.minecraft.world.phys.Vec3D.e(Vec3D.java:79)
[08:41:15] [Timer-2/WARN]: 	at net.minecraft.world.phys.shapes.VoxelShape.rayTrace(VoxelShape.java:129)
[08:41:15] [Timer-2/WARN]: 	at net.minecraft.world.level.IBlockAccess.rayTrace(IBlockAccess.java:124)
[08:41:15] [Timer-2/WARN]: 	at net.minecraft.world.level.IBlockAccess.rayTraceBlock(IBlockAccess.java:102)
[08:41:15] [Timer-2/WARN]: 	at net.minecraft.world.level.IBlockAccess.lambda$clip$2(IBlockAccess.java:114)
[08:41:15] [Timer-2/WARN]: 	at net.minecraft.world.level.IBlockAccess$$Lambda$5169/0x00000000497e8308.apply(Unknown Source)
[08:41:15] [Timer-2/WARN]: 	at net.minecraft.world.level.IBlockAccess.a(IBlockAccess.java:210)
[08:41:15] [Timer-2/WARN]: 	at net.minecraft.world.level.IBlockAccess.rayTrace(IBlockAccess.java:113)
[08:41:15] [Timer-2/WARN]: 	at Wraith.jar//dev.lone.wraith.h.a.c.a.k.b(SourceFile:89)
[08:41:15] [Timer-2/WARN]: 	at Wraith.jar//dev.lone.wraith.h.a.c.a.a(SourceFile:85)
[08:41:15] [Timer-2/WARN]: 	at Wraith.jar//dev.lone.wraith.h.a.c.a.a(SourceFile:75)
[08:41:15] [Timer-2/WARN]: 	at Wraith.jar//dev.lone.wraith.f.j.a(SourceFile:948)
[08:41:15] [Timer-2/WARN]: 	at Wraith.jar//dev.lone.wraith.f.j.H(SourceFile:898)
[08:41:15] [Timer-2/WARN]: 	at Wraith.jar//dev.lone.wraith.f.j.Z(SourceFile:173)
[08:41:15] [Timer-2/WARN]: 	at Wraith.jar//dev.lone.wraith.f.e.run(SourceFile:137)
[08:41:18] [Timer-2/WARN]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[08:41:18] [Timer-2/WARN]: 	at java.base/java.util.TimerThread.run(Timer.java:506)
```

I installed it on my fakelobby server for only login and I am giving 500MB of RAM. After a long time, I get this error and get a "Java heap space" error and my server crashes. What is the problem? Is there a RAM leak? Why am I getting this error?

**Info (please complete the following information):**
 - Server version: 1.17.1
 - Plugin version: Wraith version 2.2.6

**Comment by LoneDev6** [comment]
Seems to be a memory leak about raytracing, I'll try to find a solution but it might be also a Minecraft bug.

**Comment by LoneDev6** [comment]
Note that 500MB is very low for a 1.17.1 server. You should have at least 1024MB.
Let me know if this fixes the issue. Thanks!
