### ISSUE TITLE
Plugn does not work for 1.18.1 servers[BUG] 

### ISSUE THREAD

**Issue by CloudeLecaw** [LoneDev6/Issues-Wraith#56]
**Describe the bug**
The okugin throws errors on starting for 1.18.1 servers

**To Reproduce**
1. Start the server
2. Try any wraith command u like

**Info (please complete the following information):**
 - Server version: papermc 1.18?1
 - Plugin version: 2.2.6
 - loneDevsLibs (latest release from yesterday for 1.18 severs)

**Log file**
```
[16:28:46] [Server thread/INFO]: [Wraith] Enabling Wraith v2.2.6
[16:28:46] [Server thread/INFO]: ???????
[16:28:46] [Server thread/INFO]: ???????
[16:28:46] [Server thread/INFO]: ??????? Wraith > haunts every hacker
[16:28:46] [Server thread/INFO]: ??????? Version: 2.2.6
[16:28:46] [Server thread/INFO]: ???????
[16:28:46] [Server thread/WARN]: [Wraith] It's advised to install PacketLimiter to block packet spam and lag (nuke, crashers...). Download: https://bit.ly/wrpacklim
[16:28:46] [Server thread/INFO]: [Wraith] Found version v1_18_R1
[16:28:46] [Server thread/ERROR]: Error occurred while enabling Wraith v2.2.6 (Is it up to date?)
java.lang.RuntimeException: Failed to find PlayerConnection.sendPacket()
    at dev.lone.wraith.OtherPlugins.net.badlion.blcmodapibukkit.a.a.<init>(SourceFile:182) ~[Wraith_2.2.6.jar:?]
    at dev.lone.wraith.OtherPlugins.net.badlion.blcmodapibukkit.a.a(SourceFile:44) ~[Wraith_2.2.6.jar:?]
    at dev.lone.wraith.b.a.b.f.<init>(SourceFile:119) ~[Wraith_2.2.6.jar:?]
    at dev.lone.wraith.b.d.a(SourceFile:77) ~[Wraith_2.2.6.jar:?]
    at dev.lone.wraith.Main.onEnable(SourceFile:363) ~[Wraith_2.2.6.jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.18.1.jar:git-Paper-69]
    at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.18.1.jar:git-Paper-69]
    at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-69]
    at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-69]
    at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-69]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-69]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-69]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:28:46] [Server thread/INFO]: [Wraith] Disabling Wraith v2.2.6
```
.
```
[16:34:23] [Server thread/INFO]: Blueeyestar issued server command: /ww info blueeyestar
[16:34:23] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'ww' in plugin Wraith v2.2.6 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:876) ~[paper-1.18.1.jar:git-Paper-69]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2268) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2079) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2060) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-69]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-69]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-69]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-69]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-69]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1462) ~[paper-1.18.1.jar:git-Paper-69]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-69]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-69]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by LoneDev6** [comment]
Wraith is not updated to 1.18.1 yet.
I'll work on an update as soon as possible
