### ISSUE TITLE
[BUG] Compatible with ProtocolLib 1.18.1? | [PacketFilterManager] [Wraith] Unsupported client packet in current Minecraft version

### ISSUE THREAD

**Issue by Futodama** [LoneDev6/Issues-Wraith#57]
[16:22:26] [Server thread/WARN]: [ProtocolLib] [PacketFilterManager] [Wraith] Unsupported client packet in current Minecraft version: FLYING[PLAY, CLIENT, 254, classNames: [net.minecraft.network.protocol.game.PacketPlayInFlying, net.minecraft.network.protocol.game.ServerboundFlyingPacket, net.minecraft.network.play.client.CPacketPlayer] (unregistered)]
[16:22:26] [Server thread/WARN]: java.lang.Exception: Not an error! This is the call stack.
	at ProtocolLib.jar//com.comphenix.protocol.error.DetailedErrorReporter.printCallStack(DetailedErrorReporter.java:422)
	at ProtocolLib.jar//com.comphenix.protocol.error.DetailedErrorReporter.printCallStack(DetailedErrorReporter.java:411)
	at ProtocolLib.jar//com.comphenix.protocol.error.DetailedErrorReporter.reportLevel(DetailedErrorReporter.java:290)
	at ProtocolLib.jar//com.comphenix.protocol.error.DetailedErrorReporter.reportWarning(DetailedErrorReporter.java:253)
	at ProtocolLib.jar//com.comphenix.protocol.error.DelegatedErrorReporter.reportWarning(DelegatedErrorReporter.java:54)
	at ProtocolLib.jar//com.comphenix.protocol.error.DelegatedErrorReporter.reportWarning(DelegatedErrorReporter.java:82)
	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.enablePacketFilters(PacketFilterManager.java:583)
	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.addPacketListener(PacketFilterManager.java:342)
	at Wraith.jar//dev.lone.wraith.main.cs.r(SourceFile:107)
	at Wraith.jar//dev.lone.wraith.main.cs.<init>(SourceFile:100)
	at Wraith.jar//dev.lone.wraith.Main.onEnable(SourceFile:354)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:833)
	
	Spigot Paper-1.18.1 #101

**Comment by LoneDev6** [comment]
>  java.lang.Exception: Not an error! This is the call stack.

Update ProtocoLib.

**Comment by Futodama** [comment]
This is the latest version
https://github.com/dmulloy2/ProtocolLib/releases

**Comment by Futodama** [comment]
Latest Dev build of ProtocolLib: https://ci.dmulloy2.net/job/ProtocolLib/

[17:02:31 WARN]: [ProtocolLib] [PacketFilterManager] [Wraith] Unsupported client packet in current Minecraft version: FLYING[PLAY, CLIENT, 254, classNames: [net.minecraft.network.protocol.game.PacketPlayInFlying, net.minecraft.network.protocol.game.ServerboundFlyingPacket, net.minecraft.network.play.client.CPacketPlayer] (unregistered)]
[17:02:31 WARN]: java.lang.Exception: Not an error! This is the call stack.
        at ProtocolLib.jar//com.comphenix.protocol.error.DetailedErrorReporter.printCallStack(DetailedErrorReporter.java:422)
        at ProtocolLib.jar//com.comphenix.protocol.error.DetailedErrorReporter.printCallStack(DetailedErrorReporter.java:411)
        at ProtocolLib.jar//com.comphenix.protocol.error.DetailedErrorReporter.reportLevel(DetailedErrorReporter.java:290)
        at ProtocolLib.jar//com.comphenix.protocol.error.DetailedErrorReporter.reportWarning(DetailedErrorReporter.java:253)
        at ProtocolLib.jar//com.comphenix.protocol.error.DelegatedErrorReporter.reportWarning(DelegatedErrorReporter.java:54)
        at ProtocolLib.jar//com.comphenix.protocol.error.DelegatedErrorReporter.reportWarning(DelegatedErrorReporter.java:82)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.enablePacketFilters(PacketFilterManager.java:583)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.addPacketListener(PacketFilterManager.java:342)
        at Wraith.jar//dev.lone.wraith.main.cs.r(SourceFile:107)
        at Wraith.jar//dev.lone.wraith.main.cs.<init>(SourceFile:100)
        at Wraith.jar//dev.lone.wraith.Main.onEnable(SourceFile:354)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Futodama** [comment]
@LoneDev6 I tested the latest dev build of ProtocolLib. If you don't believe me, check it yourself, I can even send you the last console log.

**Comment by LoneDev6** [comment]
Thanks I'll try to reproduce this issue in the next days and provide a fix if needed

**Comment by LoneDev6** [comment]
This is not a bug, it's just a warning don't worry.
I'll disable this warning in future updates.

It's about the fact that your server is new and a particular feature got disabled.
