### ISSUE TITLE
[BUG] No field with type int exists in class killaura bot

### ISSUE THREAD

**Issue by supercoolspy** [LoneDev6/Issues-Wraith#76]
**Describe the bug**

**To Reproduce**
1. Create a server with spigot 1.8.8
2. Add wrath and dependencies
3. run /ww killaurabot <playerwithoutbypassperms>

**Expected behavior**
Bot spawns and despawns

**Screenshots**
![image](https://user-images.githubusercontent.com/66487448/177205282-6588d952-e4c8-4e97-899e-151be9b2ed13.png)

**Info (please complete the following information):**
 - Server version: spigot 1.8.8
 - Client version: Lunar Client 1.8.8
 - Plugin version: 2.3.1

**Additional context**
Seems to be caused by reading an int with protocol lib that doesn't exist
Caused by: com.comphenix.protocol.reflect.FieldAccessException: No field with type int exists in class PacketPlayOutEntityDestroy.
        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:369) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:349) ~[?:?]
        at dev.lone.wraith.NMS.NPC.m(SourceFile:194) ~[?:?]
        at dev.lone.wraith.NMS.NPC.d(SourceFile:83) ~[?:?]
        at dev.lone.wraith.main.bU.c(SourceFile:514) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-21fe707-741a1bd]
        ... 12 more

**Comment by LoneDev6** [comment]
This will be fixed, thanks
