### ISSUE TITLE
[ERROR] When i tried to start plugin.

### ISSUE THREAD

**Issue by ovitorfrugoli** [LoneDev6/Issues-Wraith#8]
**Describe the bug**
Just a console error.

**To Reproduce**
I started the plugin and recieve this error (i've tested 'LoneDevCheck' before buying it)

**Expected behavior**
The plugin starts

**Screenshots**
![image](https://user-images.githubusercontent.com/36685887/86851862-10e9d080-c08a-11ea-9887-695d06912f59.png)
![image](https://user-images.githubusercontent.com/36685887/86851899-23fca080-c08a-11ea-8e17-2128b7e6e581.png)

**Info (please complete the following information):**
 - Server version: spigot 1.15.2
 - Client version: fabric 1.15.2
 - Plugin version: 2.0.13

**Additional context**
> [19:39:34] [Server thread/INFO]: [Wraith] Enabling Wraith v2.0.13
> [19:39:35] [Server thread/ERROR]: Error occurred while enabling Wraith v2.0.13 (Is it up to date?)
java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.copyInputStreamToFile(Ljava/io/InputStream;Ljava/io/File;)V
at dev.lone.wraith.f.b.T(SourceFile:95) ~[?:?]
at dev.lone.wraith.f.b.<init>(SourceFile:63) ~[?:?]
at dev.lone.wraith.Main.onEnable(SourceFile:87) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:git-Spigot-800b93f-8160e29]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) ~[spigot.jar:git-Spigot-800b93f-8160e29]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) ~[spigot.jar:git-Spigot-800b93f-8160e29]
at net.frankheijden.serverutils.managers.PluginManager.enablePlugin(PluginManager.java:146) ~[?:?]
at net.frankheijden.serverutils.managers.PluginManager.reloadPlugin(PluginManager.java:183) ~[?:?]
at net.frankheijden.serverutils.managers.PluginManager.reloadPlugin(PluginManager.java:161) ~[?:?]
at net.frankheijden.serverutils.commands.CommandServerUtils.onReloadPlugin(CommandServerUtils.java:190) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
at net.frankheijden.serverutils.acf.RegisteredCommand.invoke(RegisteredCommand.java:154) ~[?:?]
at net.frankheijden.serverutils.acf.BaseCommand.executeCommand(BaseCommand.java:577) ~[?:?]
at net.frankheijden.serverutils.acf.BaseCommand.execute(BaseCommand.java:513) ~[?:?]
at net.frankheijden.serverutils.acf.RootCommand.execute(RootCommand.java:99) ~[?:?]
at net.frankheijden.serverutils.acf.BukkitRootCommand.execute(BukkitRootCommand.java:79) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot.jar:git-Spigot-800b93f-8160e29]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:711) ~[spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1657) ~[spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1497) ~[spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot.jar:git-Spigot-800b93f-8160e29]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by ovitorfrugoli** [comment]
Nevermind, i fixed it.
