### ISSUE TITLE
Plugin doesn run on 1.19.4[BUG] 

### ISSUE THREAD

**Issue by CloudeLecaw** [LoneDev6/Issues-Wraith#99]
Please add compatibility for 1.19.4

```
[02:27:53] [Server thread/INFO]: [Wraith] Enabling Wraith v2.3.4
[02:27:53] [Server thread/ERROR]: [Wraith] Error getting implementation for class dev.lone.wraith.NMS.Player.PlayerNMS - NMS v1_19_R3
[02:27:53] [Server thread/WARN]: java.lang.ClassNotFoundException: dev.lone.wraith.NMS.Player.impl.v1_19_R3
[02:27:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183)
[02:27:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
[02:27:53] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[02:27:53] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[02:27:53] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:383)
[02:27:53] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:376)
[02:27:53] [Server thread/WARN]: 	at Wraith_2.3.4.jar//dev.lone.wraith.NMS.Nms.a(SourceFile:80)
[02:27:53] [Server thread/WARN]: 	at Wraith_2.3.4.jar//dev.lone.wraith.NMS.Nms.a(SourceFile:60)
[02:27:53] [Server thread/WARN]: 	at Wraith_2.3.4.jar//dev.lone.wraith.NMS.Player.PlayerNMS.<init>(SourceFile:28)
[02:27:53] [Server thread/WARN]: 	at Wraith_2.3.4.jar//dev.lone.wraith.NMS.Player.PlayerNMS.a(SourceFile:22)
[02:27:53] [Server thread/WARN]: 	at Wraith_2.3.4.jar//dev.lone.wraith.Main.onEnable(SourceFile:180)
[02:27:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279)
[02:27:53] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192)
[02:27:53] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[02:27:53] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[02:27:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555)
[02:27:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466)
[02:27:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:637)
[02:27:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436)
[02:27:53] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[02:27:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1103)
[02:27:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[02:27:53] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[02:27:53] [Server thread/INFO]: [Wraith] Disabling Wraith v2.3.4
[02:27:53] [Server thread/ERROR]: [31m[Minecraft] Error occurred (in the plugin loader) while disabling Wraith v2.3.4 (Is it up to date?)[0m
java.lang.NullPointerException: Cannot invoke "dev.lone.wraith.main.bU.ag()" because "dev.lone.wraith.Main.a" is null
	at dev.lone.wraith.Main.onDisable(SourceFile:417) ~[Wraith_2.3.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:227) ~[paper-1.19.4.jar:git-Paper-453]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.19.4.jar:git-Paper-453]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at dev.lone.wraith.NMS.Nms.a(SourceFile:99) ~[Wraith_2.3.4.jar:?]
	at dev.lone.wraith.NMS.Nms.a(SourceFile:60) ~[Wraith_2.3.4.jar:?]
	at dev.lone.wraith.NMS.Player.PlayerNMS.<init>(SourceFile:28) ~[Wraith_2.3.4.jar:?]
	at dev.lone.wraith.NMS.Player.PlayerNMS.a(SourceFile:22) ~[Wraith_2.3.4.jar:?]
	at dev.lone.wraith.Main.onEnable(SourceFile:180) ~[Wraith_2.3.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.4.jar:git-Paper-453]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-453]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555) ~[paper-1.19.4.jar:git-Paper-453]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466) ~[paper-1.19.4.jar:git-Paper-453]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:637) ~[paper-1.19.4.jar:git-Paper-453]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[paper-1.19.4.jar:git-Paper-453]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-453]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1103) ~[paper-1.19.4.jar:git-Paper-453]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.19.4.jar:git-Paper-453]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:27:53] [Server thread/ERROR]: [Wraith] Error getting implementation for class dev.lone.wraith.NMS.Server.ServerNMS - NMS v1_19_R3
[02:27:53] [Server thread/WARN]: java.lang.ClassNotFoundException: dev.lone.wraith.NMS.Server.impl.v1_19_R3
[02:27:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183)
[02:27:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
[02:27:53] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[02:27:53] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[02:27:53] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:383)
[02:27:53] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:376)
[02:27:53] [Server thread/WARN]: 	at Wraith_2.3.4.jar//dev.lone.wraith.NMS.Nms.a(SourceFile:80)
[02:27:53] [Server thread/WARN]: 	at Wraith_2.3.4.jar//dev.lone.wraith.NMS.Nms.a(SourceFile:60)
[02:27:53] [Server thread/WARN]: 	at Wraith_2.3.4.jar//dev.lone.wraith.NMS.Server.ServerNMS.<init>(SourceFile:20)
[02:27:53] [Server thread/WARN]: 	at Wraith_2.3.4.jar//dev.lone.wraith.NMS.Server.ServerNMS.a(SourceFile:14)
[02:27:53] [Server thread/WARN]: 	at Wraith_2.3.4.jar//dev.lone.wraith.Main.onEnable(SourceFile:181)
[02:27:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279)
[02:27:53] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192)
[02:27:53] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[02:27:53] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[02:27:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555)
[02:27:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466)
[02:27:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:637)
[02:27:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436)
[02:27:53] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[02:27:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1103)
[02:27:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[02:27:53] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[02:27:53] [Server thread/INFO]: ███████
[02:27:53] [Server thread/INFO]: ███████
[02:27:53] [Server thread/INFO]: ██▀██▀█ Wraith > haunts every hacker
[02:27:53] [Server thread/INFO]: ███████ Version: 2.3.4
[02:27:53] [Server thread/INFO]: ███████
[02:27:53] [Server thread/ERROR]: [31m[Minecraft] Error occurred while enabling Wraith v2.3.4 (Is it up to date?)[0m
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register dev.lone.wraith.main.bU@7188e47d while not enabled
	at io.papermc.paper.plugin.manager.PaperEventManager.registerEvents(PaperEventManager.java:80) ~[paper-1.19.4.jar:git-Paper-453]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.registerEvents(PaperPluginManagerImpl.java:131) ~[paper-1.19.4.jar:git-Paper-453]
	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:670) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at dev.lone.wraith.main.df.a(SourceFile:16) ~[Wraith_2.3.4.jar:?]
	at dev.lone.wraith.main.bU.k(SourceFile:71) ~[Wraith_2.3.4.jar:?]
	at dev.lone.wraith.main.bU.<init>(SourceFile:66) ~[Wraith_2.3.4.jar:?]
	at dev.lone.wraith.Main.onEnable(SourceFile:318) ~[Wraith_2.3.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.4.jar:git-Paper-453]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-453]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555) ~[paper-1.19.4.jar:git-Paper-453]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466) ~[paper-1.19.4.jar:git-Paper-453]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:637) ~[paper-1.19.4.jar:git-Paper-453]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[paper-1.19.4.jar:git-Paper-453]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-453]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1103) ~[paper-1.19.4.jar:git-Paper-453]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.19.4.jar:git-Paper-453]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by LoneDev6** [comment]
Will be added, anyway the game changed so much during time that I'm thinking about removing most outdated features from the anticheat and keep only the correctly working ones.

**Comment by LoneDev6** [comment]
Update LoneLibs and update Wraith to the new version.
